version: '3.4'

services:
  ordermanagementservice:
    image: ordermanagementservice
    build:
      context: order-service-example-master
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8000:8000
